### ISSUE TITLE
Add aspectRatio utility

### ISSUE THREAD

**Issue by AlfonzAlfonz** [gregberge/xstyled#233]
## 🚀 Feature Proposal

Add aspectRatio utility to the xstyled. It should either be implemented using native aspect-ratio or with padding-top workaround. @supports query can be used to create fallback for older browsers.

**Implementation with fallback in native css**
```css
.element {
  aspect-ratio: 1 / 1;
}

@supports not (aspect-ratio: 1 / 1) {
  .element::before {
    float: left;
    padding-top: 100%;
    content: "";
  }

  .element::after {
    display: block;
    content: "";
    clear: both;
  }
}
```
[source](https://css-tricks.com/almanac/properties/a/aspect-ratio/#dealing-with-legacy-browser-support)

## Motivation

Aspect-ratio is a way to set the aspect ratio of an element. It is a part of the official CSS specification and it's gaining support in browsers.

## Example

```jsx
<x.div aspectRatio={9 / 16}>...</div>
```

## Pitch

Aspect ratio is a useful CSS rule and it would be nice to be able to use it in xstyled. Tailwind right now implements aspect ratio as an [official plugin](https://github.com/tailwindlabs/tailwindcss-aspect-ratio).
